/**
 * Gemini Image Generation Service
 * 
 * Generates images using Google's Gemini Flash Image API
 * Falls back gracefully if API key is not configured
 */

import type { ImageGenerationOptions, ImageGenerationResult, GeminiImageResponse } from '../types';
import { supabaseAdmin } from '@/lib/supabase-server';

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta';
const GEMINI_MODEL = 'gemini-2.0-flash-preview-image-generation';

// Estimated cost per image in USD
const COST_PER_IMAGE = 0.03;

/**
 * Check if image generation is available (API key configured)
 */
export function isImageGenerationAvailable(): boolean {
  return !!process.env.GEMINI_API_KEY;
}

/**
 * Get aspect ratio dimensions
 */
function getDimensions(aspectRatio?: string): { width: number; height: number } {
  const baseSize = 1024;
  
  switch (aspectRatio) {
    case '1:1':
      return { width: baseSize, height: baseSize };
    case '4:3':
      return { width: baseSize, height: Math.round(baseSize * 3 / 4) };
    case '16:9':
      return { width: baseSize, height: Math.round(baseSize * 9 / 16) };
    case '9:16':
      return { height: baseSize, width: Math.round(baseSize * 9 / 16) };
    default:
      return { width: baseSize, height: baseSize };
  }
}

/**
 * Enhance prompt with dimensions and quality instructions
 */
function enhancePrompt(prompt: string, options: ImageGenerationOptions): string {
  const dims = getDimensions(options.aspectRatio);
  
  // Add dimension context to help with generation
  return `${prompt}

Generate a high-quality image with dimensions ${dims.width}x${dims.height}.
Style: Professional, clean, suitable for project documentation.
No text, watermarks, or logos unless explicitly requested.`;
}

/**
 * Generate image using Gemini Flash Image API
 */
export async function generateImage(
  options: ImageGenerationOptions,
  userId?: string
): Promise<ImageGenerationResult> {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    return {
      success: false,
      error: 'Image generation is not configured. Please set GEMINI_API_KEY environment variable.',
    };
  }

  if (!options.prompt || options.prompt.trim().length === 0) {
    return {
      success: false,
      error: 'Prompt is required for image generation',
    };
  }

  try {
    const enhancedPrompt = enhancePrompt(options.prompt, options);
    const dims = getDimensions(options.aspectRatio);

    const requestBody = {
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: enhancedPrompt,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 1.0,
        topP: 0.95,
        topK: 40,
        maxOutputTokens: 8192,
        responseModalities: ['Text', 'Image'],
      },
    };

    const response = await fetch(
      `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      }
    );

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Gemini API error:', errorData);
      return {
        success: false,
        error: `Gemini API error: ${errorData.error?.message || response.statusText}`,
      };
    }

    const data: GeminiImageResponse = await response.json();

    // Check for API-level errors
    if (data.error) {
      console.error('Gemini API returned error:', data.error);
      return {
        success: false,
        error: `Gemini API error: ${data.error.message}`,
      };
    }

    // Extract image data from response
    const candidate = data.candidates?.[0];
    if (!candidate) {
      return {
        success: false,
        error: 'No image generated by Gemini API',
      };
    }

    // Find the image part in the response
    const imagePart = candidate.content?.parts?.find(part => part.inlineData);
    
    if (!imagePart?.inlineData?.data) {
      // Check if there's text response explaining why no image
      const textPart = candidate.content?.parts?.find(part => part.text);
      if (textPart?.text) {
        return {
          success: false,
          error: `Image generation failed: ${textPart.text}`,
        };
      }
      return {
        success: false,
        error: 'No image data in Gemini response',
      };
    }

    // Decode base64 image data
    const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');
    
    // Get token usage if available
    const tokensUsed = data.usageMetadata?.totalTokenCount || 0;

    return {
      success: true,
      costEstimate: COST_PER_IMAGE,
      // Return buffer for further processing/upload
      asset: {
        id: '', // Will be set after DB insert
        type: 'generated_image',
        prompt: options.prompt,
        storage_path: '', // Will be set after upload
        storage_bucket: 'media-assets',
        gemini_model: GEMINI_MODEL,
        tokens_used: tokensUsed,
        cost_usd: COST_PER_IMAGE,
        metadata: {
          width: dims.width,
          height: dims.height,
          aspectRatio: options.aspectRatio || '1:1',
          mimeType: imagePart.inlineData.mimeType || 'image/png',
        },
        created_by: userId,
        created_at: new Date().toISOString(),
      } as any, // Type assertion for buffer storage
      // Attach buffer for the API route to handle upload
      _buffer: imageBuffer,
    } as ImageGenerationResult & { _buffer?: Buffer };

  } catch (error) {
    console.error('Error generating image:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error during image generation',
    };
  }
}

/**
 * Generate a placeholder/fallback image when Gemini is unavailable
 * Returns a simple colored SVG as PNG buffer
 */
export async function generatePlaceholderImage(
  options: ImageGenerationOptions
): Promise<Buffer> {
  const dims = getDimensions(options.aspectRatio);
  const text = options.prompt.slice(0, 50) + (options.prompt.length > 50 ? '...' : '');
  
  // Create a simple SVG
  const svg = `
    <svg width="${dims.width}" height="${dims.height}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#fbbf24;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#f59e0b;stop-opacity:1" />
        </linearGradient>
      </defs>
      <rect width="100%" height="100%" fill="url(#grad)"/>
      <rect x="20" y="20" width="${dims.width - 40}" height="${dims.height - 40}" 
            fill="none" stroke="white" stroke-width="4" stroke-dasharray="10,5"/>
      <text x="50%" y="45%" font-family="system-ui, sans-serif" font-size="24" 
            fill="white" text-anchor="middle" font-weight="bold">
        🍌 Nano Banana
      </text>
      <text x="50%" y="55%" font-family="system-ui, sans-serif" font-size="14" 
            fill="white" text-anchor="middle">
        ${text.replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c] || c))}
      </text>
      <text x="50%" y="65%" font-family="system-ui, sans-serif" font-size="12" 
            fill="rgba(255,255,255,0.8)" text-anchor="middle">
        (Image generation not configured)
      </text>
    </svg>
  `;

  // Convert SVG to PNG using sharp if available, otherwise return SVG buffer
  try {
    // Try to use sharp if available
    const sharp = require('sharp');
    return await sharp(Buffer.from(svg)).png().toBuffer();
  } catch {
    // Fallback: return SVG as buffer (caller should handle)
    return Buffer.from(svg);
  }
}
